#'''                             Description
#        Script to calculate the percentage of the genome corresponding to 
#        each TE subclass and generate a comparative graphical representation 
#        in treemap format.
#        The table "subclass_TEs-all.tsv" generated by the Python script 
#        "porcent_per_classTE.py" included in this repository is required.
#'''

# 1. Load required libraries
# If not installed, use: install.packages(c("ggplot2", "treemapify", "tidyr", "dplyr"))
library(ggplot2)
library(treemapify)
library(tidyr)
library(dplyr)

# 2. Read the table generated by the Python script 'porcent_per_classTE.py'
df <- read.table("subclass_TEs-all.tsv", header = TRUE, sep = "\t", check.names = FALSE)

# 3. DEFINE GENOME SIZES (in bp)
genome_sizes <- c(
  "Rice"      = 374422835, 
  "Sorghum"   = 709344700,
  "Maize"     = 2182786008,
  "CC-01-1940" = 903619661,
  "R570"      = 5038506984,
  "KK3"       = 7019118486,
  "SP80-3280" = 9219554718,
  "AP85-441"  = 2761164190,
  "Np-X"      = 3924189457,
  "GXS87-16"  = 6804885551,
  "LA-Purple" = 9122613632
)

# 4. Reshape data (Wide to Long) and calculate percentages
df_long <- df %>%
  pivot_longer(cols = -Class_TE, names_to = "Species", values_to = "Bases") %>%
  mutate(
    Genome_Size = genome_sizes[Species],
    Percentage = (Bases / Genome_Size) * 100
  )

# 4.1 Calculate the remaining genome portion to complete 100%
df_other <- df_long %>%
  group_by(Species, Genome_Size) %>%
  summarise(Total_TEs = sum(Bases), .groups = "drop") %>%
  mutate(
    Class_TE = "Non-TEs",
    Bases = Genome_Size - Total_TEs,
    Percentage = (Bases / Genome_Size) * 100
  ) %>%
  select(Class_TE, Species, Bases, Genome_Size, Percentage)

# 4.2 Combine TE annotations with the "Other" portion
df_complete <- bind_rows(df_long, df_other)

# 4.3 Enforce species order
desired_order <- c("Rice", "Sorghum", "Maize", "CC-01-1940", "R570", 
                   "KK3", "SP80-3280", "AP85-441", "Np-X", "GXS87-16", 
                   "LA-Purple") 

# Convert Species column to factor with fixed order
df_complete$Species <- factor(df_complete$Species, levels = desired_order)

# 4.4 Enforce legend order
class_order <- c("DNA", "RC/Helitron", "LTR", "LINE", "SINE", "Unknown", "Non-TEs")

# Convert Class_TE column to factor with desired order
df_complete$Class_TE <- factor(df_complete$Class_TE, levels = class_order)

# 5. Create Treemap
ggplot(df_complete, aes(area = Percentage, fill = Class_TE, 
                        label = paste0(Class_TE, "\n", round(Percentage, 2), "%"),
                        subgroup = Species)) +
  geom_treemap() +
  # Add borders to separate species
  geom_treemap_subgroup_border(colour = "white", size = 3) +
  # Add species labels
  geom_treemap_subgroup_text(place = "bottomleft", size = 16, grow = FALSE, 
                             alpha = 1, colour = "white", 
                             fontface = "bold.italic") +
  # Add class labels and percentages
  geom_treemap_text(colour = "black", place = "centre", 
                    size = 11, grow = FALSE, reflow = TRUE) +
  # Aesthetics
  scale_fill_brewer(palette = "Set2") +               # Color palette
  labs(title = "TE distribution by species (% of genome)",
       fill = "TE subclass: ") +
  
  # Legend settings
  theme(legend.position = "bottom",
        legend.box = "horizontal") +
  guides(fill = guide_legend(nrow = 1, byrow = TRUE)) # Force single row

# 6. Save plot
# ggsave("treemap_TEs.png", width = 12, height = 8, dpi = 300)
