#!/usr/bin/env python3 

''' 
                                    Description 
        Script used to rename sequences from the full-length TE library in sugarcane 
        generated by TEdistill.
        The library 'distilledTE.flTE.fa' and the tabulated report 'summary_decisions.tsv' 
        generated by the script 'summarize_TEsLib.py' are required, both available in this 
        repository.
        Generates a reclassified full-length TE sequence library for sugarcane: 
        'distilledTE.flTE.renamed.fa'.
'''

import sys

def main():
    # File names
    file_tsv = "summary_decisions.tsv"
    file_fasta_in = "TEdistill/distilledTE.flTE.fa"
    file_fasta_out = "distilledTE.flTE.renamed.fa"

    mapping = {}

    # 1. Read TSV and map ID -> Final Decision (Column 6)
    try:
        with open(file_tsv, 'r') as f:
            for line in f:
                parts = line.strip().split('\t')
                if len(parts) < 6:
                    continue
                
                # ID is always the part before '#' in the first column
                id_seq = parts[0].split('#')[0]
                # Final decision is in the sixth column (index 5)
                final_name = parts[5]
                
                mapping[id_seq] = final_name
    except FileNotFoundError:
        print(f"Error: File '{file_tsv}' not found.")
        return

    # 2. Read FASTA and write new file with updated headers
    count_updated = 0
    count_total = 0

    try:
        with open(file_fasta_in, 'r') as f_in, open(file_fasta_out, 'w') as f_out:
            for line in f_in:
                if line.startswith(">"):
                    count_total += 1
                    # Extract ID from current header (e.g., TE_00010016)
                    header_content = line.strip().lstrip(">")
                    current_id = header_content.split("#")[0]

                    # Check if there is a decision for this ID in the dictionary
                    if current_id in mapping:
                        new_header = f">{mapping[current_id]}\n"
                        f_out.write(new_header)
                        count_updated += 1
                    else:
                        # If not present in TSV, keep original header
                        f_out.write(line)
                else:
                    # Sequence lines (ATGC) remain unchanged
                    f_out.write(line)
                    
        print("Success!")
        print(f"Total sequences processed: {count_total}")
        print(f"Sequences renamed: {count_updated}")
        print(f"Output file: {file_fasta_out}")

    except FileNotFoundError:
        print(f"Error: File '{file_fasta_in}' not found.")

if __name__ == "__main__":
    main()
